// templates/angular/app/components/common/pagination/pagination.component.ts
import {Component, EventEmitter, Input, Output, WritableSignal} from '@angular/core';
import {RouterLink, RouterLinkActive} from "@angular/router";
import {Pagination} from "@interface/api";

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [
    RouterLink,
    RouterLinkActive
  ],
  templateUrl: './pagination.component.html',
})
export class PaginationComponent {
  @Input() pagination!: WritableSignal<Pagination>;
  @Output() handleChangePage = new EventEmitter()

  changeUri(uri: string) {
    this.handleChangePage.emit(uri)
  }
}

<div class="flex justify-center mt-8">
  <nav aria-label="Page navigation">
    <ul class="flex list-style-none">
      <li>
        <a [routerLink]="['/books']"
           [queryParams]="pageParamValue('hydra:first')"
           [routerLinkActive]="'bg-gray-200 text-gray-500 pointer-events-none'"
           (click)="changeUri(pagination()!['hydra:first'])"
           class="bg-gray block py-2 px-3 rounded"
           aria-label="First page">
          <span aria-hidden="true">&lArr;</span>First
        </a>
      </li>
      @if (pagination()!['hydra:previous']) {
        <li>
          <a [routerLink]="['/books']"
             [queryParams]="pageParamValue('hydra:previous')"
             [routerLinkActive]="'bg-gray-200 text-gray-500 pointer-events-none'"
             (click)="changeUri(pagination()!['hydra:previous'])"
             class="bg-gray block py-2 px-3 rounded"
             aria-label="Previous page">
            Previous
          </a>
        </li>
      }
      @if (pagination()!['hydra:next']) {
      <li>
        <a [routerLink]="['/books']"
           [queryParams]="pageParamValue('hydra:next')"
           [routerLinkActive]="'bg-gray-200 text-gray-500 pointer-events-none'"
           (click)="changeUri(pagination()!['hydra:next'])"
           class="bg-gray block py-2 px-3 rounded"
           aria-label="Next page">
          Next
        </a>
      </li>
      }
      <li>
        <a [routerLink]="['/books']"
           [queryParams]="pageParamValue('hydra:last')"
           [routerLinkActive]="'bg-gray-200 text-gray-500 pointer-events-none'"
           (click)="changeUri(pagination()!['hydra:last'])"
           class="bg-gray block py-2 px-3 rounded"
           aria-label="Last page">
          <span aria-hidden="true">&rAarr;</span> Last
        </a>
      </li>
    </ul>
  </nav>
</div>

// templates/next/components/common/Pagination.tsx
import Link from "next/link";
import { PagedCollection } from "../../types/collection";

interface Props {
  collection: PagedCollection<unknown>;
}

const Pagination = ({ collection }: Props) => {
  const view = collection && collection['{{{hydraPrefix}}}view'];
  if (!view) return null;

  const {
    '{{{hydraPrefix}}}first': first,
    '{{{hydraPrefix}}}previous': previous,
    '{{{hydraPrefix}}}next': next,
    '{{{hydraPrefix}}}last': last
  } = view;

  return (
    <div className="text-center">
      <nav
        className="text-xs font-bold inline-flex mx-auto divide-x-2 divide-gray-200 flex-row flex-wrap items-center justify-center mb-4 border-2 border-gray-200 rounded-2xl overflow-hidden"
        aria-label="Page navigation"
      >
        <Link
          href={first ? first : "#"}
          className={`text-black p-3 hover:text-cyan-500 hover:bg-cyan-50 ${
            previous ? "" : " text-gray-500 pointer-events-none"
          }`}
          aria-label="First page"
        >
          <span aria-hidden="true">&lArr;</span> First
        </Link>
        <Link
          href={previous ? previous : "#"}
          className={`text-black p-3 hover:text-cyan-500 hover:bg-cyan-50 ${
            previous ? "" : " text-gray-500 pointer-events-none"
          }`}
          aria-label="Previous page"
        >
          <span aria-hidden="true">&larr;</span> Previous
        </Link>
        <Link
          href={next ? next : "#"}
          className={`text-black p-3 hover:text-cyan-500 hover:bg-cyan-50 ${
            next ? "" : " text-gray-500 pointer-events-none"
          }`}
          aria-label="Next page"
        >
          Next <span aria-hidden="true">&rarr;</span>
        </Link>
        <Link
          href={last ? last : "#"}
          className={`text-black p-3 hover:text-cyan-500 hover:bg-cyan-50 ${
            next ? "" : "text-gray-500 pointer-events-none"
          }`}
          aria-label="Last page"
        >
          Last <span aria-hidden="true">&rArr;</span>
        </Link>
      </nav>
    </div>
  );
};

export default Pagination;
