// templates/vue/components/foo/Create.vue
<template>
  <div>
    <h1>New {{{ title }}}</h1>

    <div v-if="loading" class="alert alert-info" role="status">Loading...</div>
    <div v-if="error" class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> \{{ error }}</div>

    <{{{titleUcFirst}}}Form :handle-submit="create" :values="item" :errors="violations"></{{{titleUcFirst}}}Form>
    <router-link :to="{ name: '{{{titleUcFirst}}}List' }" class="btn btn-default">Back to list</router-link>
  </div>
</template>

<script>
  import {{{titleUcFirst}}}Form from './Form.vue'
  import { createNamespacedHelpers } from 'vuex'

  const { mapGetters } = createNamespacedHelpers('{{{lc}}}/create')

  export default {
    components: {
      {{{titleUcFirst}}}Form
    },
    data () {
      return {
        item: {}
      }
    },
    computed: mapGetters([
      'error',
      'loading',
      'created',
      'violations'
    ]),
    methods: {
      create: function(item) {
        this.$store.dispatch('{{{lc}}}/create/create', item)
      }
    },
    watch: {
      created: function (created) {
        if (created) {
          this.$router.push({ name: '{{{titleUcFirst}}}Update', params: { id: created['@id']} })
        }
      }
    }
  }
</script>

// templates/react/components/foo/Create.js
import React, {Component} from 'react';
import { connect } from 'react-redux';
import { Link, Redirect } from 'react-router-dom';
import Form from './Form';
import { create, loading, error } from '../../actions/{{{ lc }}}/create';

class Create extends Component {
  static propTypes = {
    error: React.PropTypes.string,
    loading: React.PropTypes.bool.isRequired,
    created: React.PropTypes.object,
    create: React.PropTypes.func.isRequired,
    reset: React.PropTypes.func.isRequired,
  };

  componentWillUnmount() {
    this.props.reset();
  }

  render() {
    if (this.props.created) {
      return <Redirect to={`edit/${encodeURIComponent(this.props.created['@id'])}`}/>;
    }

    return <div>
      <h1>New {{{ title }}}</h1>

      {this.props.loading && <div className="alert alert-info" role="status">Loading...</div>}
      {this.props.error && <div className="alert alert-danger" role="alert"><span className="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> {this.props.error}</div>}

      <Form onSubmit={this.props.create} values={this.props.item}/>
      <Link to="." className="btn btn-default">Back to list</Link>
    </div>;
  }
}

const mapStateToProps = (state) => {
  return {
    created: state.{{{ lc }}}.create.created,
    error: state.{{{ lc }}}.create.error,
    loading: state.{{{ lc }}}.create.loading,
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    create: values => dispatch(create(values)),
    reset: () => {
      dispatch(loading(false));
      dispatch(error(null));
    },
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(Create);
