// templates/vue/components/foo/FormComponent.vue
<script lang="ts" setup>
{{#if hasManyRelations}}
import FormRepeater from "@/components/common/FormRepeaterComponent.vue";
{{/if}}
import { formatDateInput } from "@/utils/date";
import type { {{titleUcFirst}} } from "@/types/{{lc}}";
import type { SubmissionErrors } from "@/types/error";
import { toRef } from "vue";

const props = defineProps<{
  values?: {{titleUcFirst}};
  errors?: SubmissionErrors;
}>();

const emit = defineEmits<{
  (e: "sendForm", item: {{titleUcFirst}}): void;
}>();

const violations = toRef(props, "errors");

let item: any = {};

if (props.values) {
  item = {
    ...props.values,
    {{#each fields}}
    {{#compare type "==" "dateTime" }}
    publicationDate: formatDateInput(props.values.publicationDate),
    {{/compare}}
    {{#if isEmbeddeds}}
    {{name}}: props.values.{{name}}?.map((item: any) => item["@id"] ?? "") ?? [],
    {{else if embedded}}
    {{name}}: props.values.{{name}}?.["@id"],
    {{/if}}
    {{/each}}
  };
}

function emitSendForm() {
  emit("sendForm", item);
}
</script>

<template>
  <form @submit.prevent="emitSendForm">
  {{#each formFields}}
    <div class="form-group">
      <label for="{{../lc}}_{{name}}" class="form-control-label">
        {{name}}
      </label>
      {{#if isManyRelations}}
      <FormRepeater
        :values="item.{{name}}"
        @update="(values) => (item.{{name}} = values)"
      />
      {{else}}
      <input
        id="{{../lc}}_{{name}}"
        v-model="item.{{name}}"
        :class="[
          'form-control',
          violations?.{{name}} ? 'is-invalid' : 'is-valid'
        ]"
        {{#compare type "==" "dateTime" }}
        type="date"
        {{/compare}}
        {{#compare type "!=" "dateTime" }}
        type="{{type}}"
        {{/compare}}
        {{#if step}}
        step="{{step}}"
        {{/if}}
        {{#if required}}
        required
        {{/if}}
        placeholder="{{description}}"
      />
      {{/if}}
      <div v-if="violations?.{{name}}" class="invalid-feedback">
        \{{ violations.{{name}} }}
      </div>
    </div>
    {{/each}}

    <button type="submit" class="btn btn-success">Submit</button>
  </form>
</template>

// templates/react/components/foo/Form.js
import React, { Component } from 'react';
import { Field, reduxForm } from 'redux-form';
import PropTypes from 'prop-types';

class Form extends Component {
  static propTypes = {
    handleSubmit: PropTypes.func.isRequired,
    error: PropTypes.string
  };

  renderField = data => {
    data.input.className = 'form-control';

    const isInvalid = data.meta.touched && !!data.meta.error;
    if (isInvalid) {
      data.input.className += ' is-invalid';
      data.input['aria-invalid'] = true;
    }

    if (this.props.error && data.meta.touched && !data.meta.error) {
      data.input.className += ' is-valid';
    }

    return (
      <div className={`form-group`}>
        <label
          htmlFor={`{{{lc}}}_${data.input.name}`}
          className="form-control-label"
        >
          {data.input.name}
        </label>
        <input
          {...data.input}
          type={data.type}
          step={data.step}
          required={data.required}
          placeholder={data.placeholder}
          id={`{{{lc}}}_${data.input.name}`}
        />
        {isInvalid && <div className="invalid-feedback">{data.meta.error}</div>}
      </div>
    );
  };

  render() {
    return (
      <form onSubmit={this.props.handleSubmit}>
{{#each formFields}}
        <Field
          component={this.renderField}
          name="{{{name}}}"
          type="{{{type}}}"{{#if step}}
          step="{{{step}}}"{{/if}}
          placeholder="{{{description}}}"{{#if required}}
          required={true}{{/if}}{{#if reference}}{{#unless maxCardinality}}
          normalize={v => v.split(',')}{{/unless}}{{/if}}
        />
{{/each}}

        <button type="submit" className="btn btn-success">
          Submit
        </button>
      </form>
    );
  }
}

export default reduxForm({
  form: '{{{lc}}}',
  enableReinitialize: true,
  keepDirtyOnReinitialize: true
})(Form);
