// templates/react-typescript/components/foo/Create.tsx
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Link, Redirect } from 'react-router-dom';
import { TError, TDispatch } from '../../utils/types';
import { I{{{ucf}}} } from '../../interfaces/{{{ucf}}}';
import { create, reset } from '../../actions/{{{lc}}}/create';
import { ICreateState } from '../../types/{{{lc}}}/create';
import Form from './Form';

interface ICreateProps {
  created: I{{{ucf}}} | null;
  loading: boolean;
  error: TError;
}

interface ICreateActions {
  reset: () => any;
  create: ({{{lc}}}: Partial<I{{{ucf}}}>) => any;
}

const mapStateToProps: (state: { {{{lc}}}: { create: ICreateState } }) => ICreateProps = state => {
  const { created, error, loading } = state.{{{lc}}}.create;
  return { created, error, loading };
};

const mapDispatchToProps: (dispatch: TDispatch) => ICreateActions = dispatch => ({
  create: values => dispatch(create(values)),
  reset: () => dispatch(reset())
});

class Create extends Component<ICreateProps & ICreateActions> {
  componentWillUnmount() {
    this.props.reset();
  }

  render() {
    if (this.props.created)
      return (
        <Redirect
          to={`edit/${encodeURIComponent(this.props.created['@id'])}`}
        />
      );

    return (
      <div>
        <h1>New {{{title}}}</h1>

        {this.props.loading && (
          <div className="alert alert-info" role="status">
            Loading...
          </div>
        )}
        {this.props.error && (
          <div className="alert alert-danger" role="alert">
            <span className="fa fa-exclamation-triangle" aria-hidden="true" />{' '}
            {this.props.error}
          </div>
        )}

        <Form onSubmit={this.props.create} />
        <Link to="." className="btn btn-primary">
          Back to list
        </Link>
      </div>
    );
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Create);

// templates/vue/components/foo/Create.vue
<template>
  <div>
    <h1>New {{{ title }}}</h1>

    <div v-if="loading" class="alert alert-info" role="status">Loading...</div>
    <div v-if="error" class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> \{{ error }}</div>

    <{{{titleUcFirst}}}Form :handle-submit="create" :values="item" :errors="violations"></{{{titleUcFirst}}}Form>
    <router-link :to="{ name: '{{{titleUcFirst}}}List' }" class="btn btn-default">Back to list</router-link>
  </div>
</template>

<script>
  import {{{titleUcFirst}}}Form from './Form.vue'
  import { createNamespacedHelpers } from 'vuex'

  const { mapGetters } = createNamespacedHelpers('{{{lc}}}/create')

  export default {
    components: {
      {{{titleUcFirst}}}Form
    },
    data () {
      return {
        item: {}
      }
    },
    computed: mapGetters([
      'error',
      'loading',
      'created',
      'violations'
    ]),
    methods: {
      create: function(item) {
        this.$store.dispatch('{{{lc}}}/create/create', item)
      }
    },
    watch: {
      created: function (created) {
        if (created) {
          this.$router.push({ name: '{{{titleUcFirst}}}Update', params: { id: created['@id']} })
        }
      }
    }
  }
</script>
