// templates/react/components/foo/Create.tsx
import { Link, Navigate } from "react-router-dom";
import { useCreate } from "../../hooks";
import Form from "./Form";
import { TError } from "../../utils/types";
import TResource from "./type";

interface CreateProps {
  created: TResource | null;
  create: (item: Partial<TResource>) => any;
  error: TError;
  reset: () => void;
  loading: boolean;
}

const CreateView = ({create, created, error, reset, loading}: CreateProps) => {
  if (created) {
    return (
      <Navigate
        to={`/{{lc}}s`}
        replace
      />
    );
  }

  return (
    <div>
      <h1>Create {{{title}}}</h1>

      {loading && (
        <div className="alert alert-info" role="status">
            Loading...
        </div>
      )}
      {error && (
        <div className="alert alert-danger" role="alert">
          <span className="fa fa-exclamation-triangle" aria-hidden="true"/>{" "}
          {error.message}
        </div>
      )}

      <Form onSubmit={create} error={error} reset={reset}/>
      <Link to="/{{lc}}s/" className="btn btn-primary">
          Back to list
      </Link>
    </div>
  );
}

const Create = () => {
  const {created, loading, error, reset, create} = useCreate<TResource>({"@id": "{{{name}}}"});

  return (
    <CreateView
      created={created}
      loading={loading}
      error={error}
      reset={reset}
      create={create}
    />
  );
}

export default Create;

// templates/vue/components/foo/CreateComponent.vue
<script lang="ts" setup>
import {{titleUcFirst}}Form from "@/components/{{lc}}/FormComponent.vue";
import { use{{titleUcFirst}}CreateStore } from "@/stores/{{lc}}/create";
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import type { {{titleUcFirst}} } from "@/types/{{lc}}";

const router = useRouter();

const {{lc}}CreateStore = use{{titleUcFirst}}CreateStore();
const { isLoading, error, violations } = storeToRefs({{lc}}CreateStore);

async function onSendForm(item: {{titleUcFirst}}) {
  await {{lc}}CreateStore.create(item);

  if (!{{lc}}CreateStore.created) return;

  router.push({
    name: "{{titleUcFirst}}Update",
    params: { id: {{lc}}CreateStore.created["@id"] },
  });
}
</script>

<template>
  <h1>Create {{title}}</h1>

  <div v-if="isLoading" class="alert alert-info" role="status">Loading...</div>
  <div v-if="error" class="alert alert-danger" role="alert">
    <i class="bi-exclamation-triangle" />
    \{{ error }}
  </div>

  <{{titleUcFirst}}Form :errors="violations" @send-form="onSendForm" />

  <router-link :to="{ name: '{{titleUcFirst}}List' }" class="btn btn-primary">
    Back to list
  </router-link>
</template>
