// templates/react/components/foo/List.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import PropTypes from 'prop-types';
import { list, reset } from '../../actions/{{{lc}}}/list';

class List extends Component {
  static propTypes = {
    retrieved: PropTypes.object,
    loading: PropTypes.bool.isRequired,
    error: PropTypes.string,
    eventSource: PropTypes.instanceOf(EventSource),
    deletedItem: PropTypes.object,
    list: PropTypes.func.isRequired,
    reset: PropTypes.func.isRequired
  };

  componentDidMount() {
    this.props.list(
      this.props.match.params.page &&
        decodeURIComponent(this.props.match.params.page)
    );
  }

  componentDidUpdate(prevProps) {
    if (this.props.match.params.page !== prevProps.match.params.page)
      this.props.list(
        this.props.match.params.page &&
          decodeURIComponent(this.props.match.params.page)
      );
  }

  componentWillUnmount() {
    this.props.reset(this.props.eventSource);
  }

  render() {
    return (
      <div>
        <h1>{{{title}}} List</h1>

        {this.props.loading && (
          <div className="alert alert-info">Loading...</div>
        )}
        {this.props.deletedItem && (
          <div className="alert alert-success">
            {this.props.deletedItem['@id']} deleted.
          </div>
        )}
        {this.props.error && (
          <div className="alert alert-danger">{this.props.error}</div>
        )}

        <p>
          <Link to="create" className="btn btn-primary">
            Create
          </Link>
        </p>

        <table className="table table-responsive table-striped table-hover">
          <thead>
            <tr>
              <th>id</th>
{{#each fields}}
              <th>{{name}}</th>
{{/each}}
              <th colSpan={2} />
            </tr>
          </thead>
          <tbody>
            {this.props.retrieved &&
              this.props.retrieved['hydra:member'].map(item => (
                <tr key={item['@id']}>
                  <th scope="row">
                    <Link to={`show/${encodeURIComponent(item['@id'])}`}>
                      {item['@id']}
                    </Link>
                  </th>
{{#each fields}}
                  <td>{{#if reference}}{this.renderLinks('{{{reference.name}}}', item['{{{name}}}'])}{{else}}{item['{{{name}}}']}{{/if}}</td>
{{/each}}
                  <td>
                    <Link to={`show/${encodeURIComponent(item['@id'])}`}>
                      <span className="fa fa-search" aria-hidden="true" />
                      <span className="sr-only">Show</span>
                    </Link>
                  </td>
                  <td>
                    <Link to={`edit/${encodeURIComponent(item['@id'])}`}>
                      <span className="fa fa-pencil" aria-hidden="true" />
                      <span className="sr-only">Edit</span>
                    </Link>
                  </td>
                </tr>
              ))}
          </tbody>
        </table>

        {this.pagination()}
      </div>
    );
  }

  pagination() {
    const view = this.props.retrieved && this.props.retrieved['hydra:view'];
    if (!view || !view['hydra:first']) return;

    const {
      'hydra:first': first,
      'hydra:previous': previous,
      'hydra:next': next,
      'hydra:last': last
    } = view;

    return (
      <nav aria-label="Page navigation">
        <Link
          to="."
          className={`btn btn-primary${previous ? '' : ' disabled'}`}
        >
          <span aria-hidden="true">&lArr;</span> First
        </Link>
        <Link
          to={
            !previous || previous === first ? '.' : encodeURIComponent(previous)
          }
          className={`btn btn-primary${previous ? '' : ' disabled'}`}
        >
          <span aria-hidden="true">&larr;</span> Previous
        </Link>
        <Link
          to={next ? encodeURIComponent(next) : '#'}
          className={`btn btn-primary${next ? '' : ' disabled'}`}
        >
          Next <span aria-hidden="true">&rarr;</span>
        </Link>
        <Link
          to={last ? encodeURIComponent(last) : '#'}
          className={`btn btn-primary${next ? '' : ' disabled'}`}
        >
          Last <span aria-hidden="true">&rArr;</span>
        </Link>
      </nav>
    );
  }

  renderLinks = (type, items) => {
    if (Array.isArray(items)) {
      return items.map((item, i) => (
        <div key={i}>{this.renderLinks(type, item)}</div>
      ));
    }

    return (
      <Link to={`../${type}/show/${encodeURIComponent(items)}`}>{items}</Link>
    );
  };
}

const mapStateToProps = state => {
  const {
    retrieved,
    loading,
    error,
    eventSource,
    deletedItem
  } = state.{{{lc}}}.list;
  return { retrieved, loading, error, eventSource, deletedItem };
};

const mapDispatchToProps = dispatch => ({
  list: page => dispatch(list(page)),
  reset: eventSource => dispatch(reset(eventSource))
});

export default connect(mapStateToProps, mapDispatchToProps)(List);

// templates/vue/components/foo/List.vue
<script lang="ts" setup>
import { use{{{titleUcFirst}}}DeleteStore } from "@/stores/{{{lc}}}/delete";
import type { {{{titleUcFirst}}} } from "@/utils/types";
import { storeToRefs } from "pinia";
import { onBeforeUnmount } from "vue";
import { use{{{titleUcFirst}}}ListStore } from "@/stores/{{{lc}}}/list";
import { mercureSubscribe } from "@/utils/mercure";

const {{{lc}}}ListStore = use{{{titleUcFirst}}}ListStore();
const { items, error, view, isLoading } = storeToRefs({{{lc}}}ListStore);

const mercureEl = (data: {{{titleUcFirst}}}) => {
  if (Object.keys(data).length === 1) {
    {{{lc}}}ListStore.deleteItem(data);
    {{{lc}}}DeleteStore.setMercureDeleted(data);
    return;
  }

  {{{lc}}}ListStore.updateItem(data);
};

let mercureSub: EventSource | null = null;

{{{lc}}}ListStore.$subscribe((mutation, state) => {
  if (!state.hubUrl) {
    return;
  }

  if (mercureSub) {
    mercureSub.close();
  }

  if (!state.items?.length) {
    return;
  }

  mercureSub = mercureSubscribe(
    state.hubUrl,
    state.items.map((i) => i["@id"] ?? ""),
    mercureEl
  );
});

await {{{lc}}}ListStore.getItems();

const {{{lc}}}DeleteStore = use{{{titleUcFirst}}}DeleteStore();
const { deleted: deletedItem, mercureDeleted: mercureDeletedItem } =
  storeToRefs({{{lc}}}DeleteStore);

onBeforeUnmount(() => {
  mercureSub?.close();
  {{{lc}}}DeleteStore.$reset();
});
</script>

<template>
  <div>
    <h1>{{{title}}} List</h1>

    <div v-if="isLoading" class="alert alert-info">Loading...</div>
    <div v-if="deletedItem" class="alert alert-success">
      \{{ deletedItem['@id'] }} deleted.
    </div>
    <div v-if="mercureDeletedItem" class="alert alert-success">
      \{{ mercureDeletedItem['@id'] }} deleted by another user.
    </div>
    <div v-if="error" class="alert alert-danger">\{{ error }}</div>

    <p>
      <router-link 
        :to="{ name: '{{{titleUcFirst}}}Create' }" 
        class="btn btn-primary"
      >
        Create
      </router-link>
    </p>

    <table class="table table-responsive table-striped table-hover">
      <thead>
        <tr>
          <th>id</th>
{{#each fields}}
          <th>{{name}}</th>
{{/each }}
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="item in items"
          :key="item['@id']"
        >
          <th scope="row">
            <router-link
              v-if="item"
              :to="{name: '{{{titleUcFirst}}}Show', params: { id: item['@id'] }}"
            >
              \{{ item['@id'] }}
            </router-link>
          </th>
{{#each fields}}
        <td>
          {{#if reference}}
            <template>
              <div v-if="Array.isArray(item['{{{reference.name}}}'])">
                <router-link
                  v-for="link in item['{{{reference.name}}}']"
                  :key="link['@id']"
                  :to="{ name: '{{{reference.title}}}Show', params: { id: link['@id'] } }"
                >
                  \{{ link['@id'] }}
                </router-link>
              </div>
              <router-link
                v-else
                :to="{ name: '{{{reference.title}}}Show', params: { id: item['{{{reference.name}}}'] } }"
              >
                \{{ item['{{{reference.name}}}'] }}
              </router-link>
            </template>
          {{else}}
            \{{ item.{{{name}}} }}
          {{/if}}
        </td>
{{/each}}
          <td>
            <router-link :to="{name: '{{{titleUcFirst}}}Show', params: { id: item['@id'] }}">
              <i class="bi-search" />
              <span class="sr-only">Show</span>
            </router-link>
          </td>
          <td>
            <router-link :to="{name: '{{{titleUcFirst}}}Update', params: { id: item['@id'] }}">
              <i class="bi-pencil" />
              <span class="sr-only">Edit</span>
            </router-link>
          </td>
        </tr>
      </tbody>
    </table>

    <nav aria-label="Page navigation" v-if="view">
      <router-link
        :to="view['hydra:first'] ? view['hydra:first'] : { name: '{{{titleUcFirst}}}List' }"
        :class="{ disabled: !view['hydra:previous'] }"
        class="btn btn-primary"
        aria-label="First page"
      >
        <span aria-hidden="true">&lArr;</span> First
      </router-link>
      &nbsp;
      <router-link
        :to="!view['hydra:previous'] || view['hydra:previous'] === view['hydra:first'] ? { name: '{{{titleUcFirst}}}List' } : view['hydra:previous']"
        :class="{ disabled: !view['hydra:previous'] }"
        class="btn btn-primary"
        aria-label="Previous page"
      >
        <span aria-hidden="true">&larr;</span> Previous
      </router-link>

      <router-link
        :to="view['hydra:next'] ? view['hydra:next'] : '#'"
        :class="{ disabled: !view['hydra:next'] }"
        class="btn btn-primary"
        aria-label="Next page"
      >
        Next <span aria-hidden="true">&rarr;</span>
      </router-link>

      <router-link
        :to="view['hydra:last'] ? view['hydra:last'] : '#'"
        :class="{ disabled: !view['hydra:next'] }"
        class="btn btn-primary"
        aria-label="Last page"
      >
        Last <span aria-hidden="true">&rArr;</span>
      </router-link>
    </nav>
  </div>
</template>
