// templates/react/components/foo/Update.js
import React, {Component} from 'react';
import { connect } from 'react-redux';
import { Link, Redirect } from 'react-router-dom';
import PropTypes from 'prop-types';
import Form from './Form';
import { success } from '../../actions/{{{ lc }}}/create';
import { retrieve, update, reset } from '../../actions/{{{ lc }}}/update';
import { del, loading, error } from '../../actions/{{{ lc }}}/delete';

class Update extends Component {
  static propTypes = {
    retrieveError: PropTypes.string,
    retrieveLoading: PropTypes.bool.isRequired,
    updateError: PropTypes.string,
    updateLoading: PropTypes.bool.isRequired,
    deleteError: PropTypes.string,
    deleteLoading: PropTypes.bool.isRequired,
    retrieved: PropTypes.object,
    updated: PropTypes.object,
    deleted: PropTypes.object,
    retrieve: PropTypes.func.isRequired,
    update: PropTypes.func.isRequired,
    del: PropTypes.func.isRequired,
    reset: PropTypes.func.isRequired,
  };

  componentDidMount() {
    this.props.retrieve(decodeURIComponent(this.props.match.params.id));
  }

  componentWillUnmount() {
    this.props.reset();
  }

  del = () => {
    if (window.confirm('Are you sure you want to delete this item?')) this.props.del(this.props.retrieved);
  };

  render() {
    if (this.props.deleted) return <Redirect to=".."/>;

    const item = this.props.updated ? this.props.updated : this.props.retrieved;

    return <div>
      <h1>Edit {item && item['@id']}</h1>

      {this.props.created && <div className="alert alert-success" role="status">{this.props.created['@id']} created.</div>}
      {this.props.updated && <div className="alert alert-success" role="status">{this.props.updated['@id']} updated.</div>}
      {(this.props.retrieveLoading || this.props.updateLoading || this.props.deleteLoading) && <div className="alert alert-info" role="status">Loading...</div>}
      {this.props.retrieveError && <div className="alert alert-danger" role="alert"><span className="fa fa-exclamation-triangle" aria-hidden="true"></span> {this.props.retrieveError}</div>}
      {this.props.updateError && <div className="alert alert-danger" role="alert"><span className="fa fa-exclamation-triangle" aria-hidden="true"></span> {this.props.updateError}</div>}
      {this.props.deleteError && <div className="alert alert-danger" role="alert"><span className="fa fa-exclamation-triangle" aria-hidden="true"></span> {this.props.deleteError}</div>}

      {item && <Form onSubmit={values => this.props.update(item, values)} initialValues={item}/>}
      <Link to=".." className="btn btn-primary">Back to list</Link>
      <button onClick={this.del} className="btn btn-danger">Delete</button>
    </div>;
  }
}

const mapStateToProps = (state) => {
  return {
    retrieveError: state.{{{ lc }}}.update.retrieveError,
    retrieveLoading: state.{{{ lc }}}.update.retrieveLoading,
    updateError: state.{{{ lc }}}.update.updateError,
    updateLoading: state.{{{ lc }}}.update.updateLoading,
    deleteError: state.{{{ lc }}}.del.error,
    deleteLoading: state.{{{ lc }}}.del.loading,
    created: state.{{{ lc }}}.create.created,
    deleted: state.{{{ lc }}}.del.deleted,
    retrieved: state.{{{ lc }}}.update.retrieved,
    updated: state.{{{ lc }}}.update.updated,
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    retrieve: id => dispatch(retrieve(id)),
    update: (item, values) => dispatch(update(item, values)),
    del: item => dispatch(del(item)),
    reset: () => {
      dispatch(reset());
      dispatch(error(null));
      dispatch(loading(false));
      dispatch(success(null));
    },
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(Update);

// templates/vue/components/foo/UpdateComponent.vue
<script lang="ts" setup>
import { onBeforeUnmount } from "vue";
import { useRoute, useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { use{{titleUcFirst}}CreateStore } from "@/stores/{{lc}}/create";
import { use{{titleUcFirst}}DeleteStore } from "@/stores/{{lc}}/delete";
import { use{{titleUcFirst}}UpdateStore } from "@/stores/{{lc}}/update";
import type { {{titleUcFirst}} } from "@/types/{{lc}}";
import {{titleUcFirst}}Form from "@/components/{{lc}}/FormComponent.vue";
import { useMercureItem } from "@/composables/mercureItem";

const route = useRoute();
const router = useRouter();

const {{lc}}CreateStore = use{{titleUcFirst}}CreateStore();
const { created } = storeToRefs({{lc}}CreateStore);

const {{lc}}DeleteStore = use{{titleUcFirst}}DeleteStore();
const { error: deleteError, isLoading: deleteLoading } =
  storeToRefs({{lc}}DeleteStore);

const {{lc}}UpdateStore = use{{titleUcFirst}}UpdateStore();
const {
  retrieved: item,
  updated,
  error,
  isLoading,
  violations,
} = storeToRefs({{lc}}UpdateStore);

useMercureItem({
  store: {{lc}}UpdateStore,
  deleteStore: {{lc}}DeleteStore,
  redirectRouteName: "{{titleUcFirst}}List",
});

await {{lc}}UpdateStore.retrieve(decodeURIComponent(route.params.id as string));

function onSendForm(item: {{titleUcFirst}}) {
  {{lc}}UpdateStore.update(item);
}

async function deleteItem() {
  if (!item?.value) {
    {{lc}}UpdateStore.setError("No {{lc}} found. Please reload");
    return;
  }

  if (window.confirm("Are you sure you want to delete this {{lc}}?")) {
    await {{lc}}DeleteStore.deleteItem(item.value);

    if ({{lc}}DeleteStore.deleted) {
      router.push({ name: "{{titleUcFirst}}List" });
    }
  }
}

onBeforeUnmount(() => {
  {{lc}}UpdateStore.$reset();
  {{lc}}CreateStore.$reset();
});
</script>

<template>
  <div>
    <h1>Edit {{titleUcFirst}} \{{ item?.["@id"] }}</h1>

    <div v-if="created" class="alert alert-success" role="status">
      \{{ created["@id"] }} created.
    </div>
    <div v-if="updated" class="alert alert-success" role="status">
      \{{ updated["@id"] }} updated.
    </div>
    <div
      v-if="isLoading || deleteLoading"
      class="alert alert-info"
      role="status"
    >
      Loading...
    </div>
    <div v-if="error" class="alert alert-danger" role="alert">
      <i class="bi-exclamation-triangle" />
      \{{ error }}
    </div>
    <div v-if="deleteError" class="alert alert-danger" role="alert">
      <i class="bi-exclamation-triangle" />
      \{{ deleteError }}
    </div>

    <{{titleUcFirst}}Form
      v-if="item"
      :values="item"
      :errors="violations"
      @send-form="onSendForm"
    />

    <router-link v-if="item" :to="{ name: '{{titleUcFirst}}List' }" class="btn btn-primary">
      Back to list
    </router-link>
    <button class="btn btn-danger" @click="deleteItem">Delete</button>
  </div>
</template>
