// templates/react/components/foo/Update.tsx
import { Link, Navigate, useParams } from "react-router-dom";
import Form from "./Form";
import { useDelete, useRetrieve, useUpdate } from "../../hooks";
import TResource from "./type";
import { TError } from "../../utils/types";

interface UpdateProps {
  retrieved: TResource | null;
  retrieveLoading: boolean;
  retrieveError: TError;
  updateLoading: boolean;
  updateError: TError;
  deleteLoading: boolean;
  deleteError: TError;
  created: TResource | null;
  updated: TResource | null;
  deleted: TResource | null;
  del: (item: TResource) => any;
  update: (item: TResource, values: Partial<TResource>) => any;
  reset: () => void;
}

const UpdateView = ({created, del, deleteError, deleteLoading, deleted, retrieveError, retrieveLoading, retrieved, update, updateError, updateLoading, updated, reset}: UpdateProps) => {
  if (deleted) {
    return <Navigate to="/{{lc}}s/" replace />;
  }

  const item = updated ? updated : retrieved;
  const delWithConfirm = () => {
    if (retrieved && window.confirm("Are you sure you want to delete this item?")) {
      del(retrieved);
    }
  };

  return (
    <div>
      <h1>Edit {{{ucf}}} {item && item["@id"]}</h1>

      {created && (
        <div className="alert alert-success" role="status">
          {created["@id"]} created.
        </div>
      )}
      {updated && (
        <div className="alert alert-success" role="status">
          {updated["@id"]} updated.
        </div>
      )}
      {(retrieveLoading ||
        updateLoading ||
        deleteLoading) && (
        <div className="alert alert-info" role="status">
           Loading...
        </div>
      )}
      {retrieveError && (
        <div className="alert alert-danger" role="alert">
          <span className="fa fa-exclamation-triangle" aria-hidden="true" />{" "}
          {retrieveError.message}
        </div>
      )}
      {updateError && (
        <div className="alert alert-danger" role="alert">
          <span className="fa fa-exclamation-triangle" aria-hidden="true" />{" "}
          {updateError.message}
        </div>
      )}
      {deleteError && (
        <div className="alert alert-danger" role="alert">
          <span className="fa fa-exclamation-triangle" aria-hidden="true" />{" "}
          {deleteError.message}
        </div>
      )}

      {item && (
        <Form
          onSubmit={values => {
            reset();
            update(item, values);
          }}
          error={updateError}
          reset={reset}
          initialValues={item}
        />
      )}
      <Link to="/{{lc}}s/" className="btn btn-primary">
        Back to list
      </Link>
      <button onClick={delWithConfirm} className="btn btn-danger">
        Delete
      </button>
    </div>
  );
}

const Update = () => {
  const { id } = useParams<{ id: string }>();
  const {retrieved, loading: retrieveLoading, error: retrieveError} = useRetrieve<TResource>(decodeURIComponent(id || ""));
  const {updated, update, reset, loading: updateLoading, error: updateError} = useUpdate<TResource>();
  const {deleted, loading: deleteLoading, error: deleteError, del} = useDelete<TResource>();

  return (
    <UpdateView
      retrieved={retrieved}
      retrieveLoading={retrieveLoading}
      retrieveError={retrieveError}
      updateLoading={updateLoading}
      updateError={updateError}
      deleteLoading={deleteLoading}
      deleteError={deleteError}
      created={null}
      updated={updated}
      deleted={deleted}
      del={del}
      update={update}
      reset={reset}
    />
  );
}

export default Update;

// templates/vue/components/foo/Update.vue
<template>
  <div>
    <h1>Edit \{{ item && item['@id'] }}</h1>

    <div v-if="created" class="alert alert-success" role="status">\{{ created['@id'] }} created.</div>
    <div v-if="updated" class="alert alert-success" role="status">\{{ updated['@id'] }} updated.</div>
    <div v-if="retrieveLoading || updateLoading || deleteLoading"class="alert alert-info" role="status">Loading...</div>
    <div v-if="retrieveError" class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> \{{ retrieveError }}</div>
    <div v-if="updateError" class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> \{{ updateError }}</div>
    <div v-if="deleteError" class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> \{{ deleteError }}</div>

    <{{{titleUcFirst}}}Form v-if="item" :handle-submit="update" :values="item" :errors="violations" :initialValues="retrieved"></{{{titleUcFirst}}}Form>
    <router-link v-if="item" :to="{ name: '{{{titleUcFirst}}}List' }" class="btn btn-default">Back to list</router-link>
    <button @click="del" class="btn btn-danger">Delete</button>
  </div>
</template>

<script>
  import {{{titleUcFirst}}}Form from './Form.vue';
  import { mapGetters } from 'vuex';

  export default {
    created () {
      this.$store.dispatch('{{{lc}}}/update/retrieve', decodeURIComponent(this.$route.params.id));
    },
    components: {
      {{{titleUcFirst}}}Form
    },
    computed: {
      ...mapGetters({
        retrieveError: '{{{lc}}}/update/retrieveError',
        retrieveLoading: '{{{lc}}}/update/retrieveLoading',
        updateError: '{{{lc}}}/update/updateError',
        updateLoading: '{{{lc}}}/update/updateLoading',
        deleteError: '{{{lc}}}/del/error',
        deleteLoading: '{{{lc}}}/del/loading',
        created: '{{{lc}}}/create/created',
        deleted: '{{{lc}}}/del/deleted',
        retrieved: '{{{lc}}}/update/retrieved',
        updated: '{{{lc}}}/update/updated',
        violations: '{{{lc}}}/update/violations'
      })
    },
    data: function() {
      return {
        item: {}
      }
    },
    methods: {
      update (values) {
        this.$store.dispatch('{{{lc}}}/update/update', {item: this.retrieved, values: values });
      },
      del () {
        if (window.confirm('Are you sure you want to delete this item?'))
          this.$store.dispatch('{{{lc}}}/del/delete', this.retrieved);
      },
      reset () {
        this.$store.dispatch('{{{lc}}}/update/reset');
        this.$store.dispatch('{{{lc}}}/del/reset');
        this.$store.dispatch('{{{lc}}}/create/reset');

      }
    },
    watch: {
      deleted: function (deleted) {
        if (deleted) {
          this.$router.push({ name: '{{{titleUcFirst}}}List' });
        }
      }
    },
    beforeDestroy() {
      this.reset();
    }
  }
</script>
